---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm run-script nodetest
